#!/bin/sh
# it should go there: ./live-build-config/kali-config/common/includes.chroot/usr/lib/live/config/0031-kali-user-setup

configure_zsh() {
    # Stop if zsh is not present
    if [ ! -x /usr/bin/zsh ]; then
	return
    fi
    # Stop if user has opted out of zsh
    if echo "${LIVE_CONFIG_CMDLINE}" | grep -qs 'nozsh'; then
	return
    fi
    chsh --shell /usr/bin/zsh kali
    chsh --shell /usr/bin/zsh root
}

configure_bash() {
    chsh --shell /usr/bin/bash kali
    chsh --shell /usr/bin/bash root
}

maaaaz_customization() {
    chown -R kali:kali /home/kali/
}

configure_usergroups() {
    # Ensure those groups exist
    addgroup --system kaboxer || true
    addgroup --system wireshark || true

    # adm - read access to log files
    # dialout - for serial port access
    # kaboxer - for kaboxer
    # vboxsf - shared folders for virtualbox guest
    # wireshark - capture sessions without being root
    kali_groups="adm dialout kaboxer vboxsf wireshark"

    for grp in $kali_groups; do
	getent group $grp >/dev/null || continue
	usermod -a -G $grp kali
    done
}

# Avoid configuring multiple times in case persistence is enabled
if [ -e /var/lib/live/config/kali-user-setup ]; then
    exit 0
fi

# Set "kali" as password for the user kali
usermod -p 'AqLUsDitNnTsw' kali

# Change default shell to zsh
#configure_zsh
configure_bash

# Add kali user to additional groups
configure_usergroups

# maaaaaz customization
maaaaz_customization

# Remember that this script has been run
touch /var/lib/live/config/kali-user-setup
